diploma/pet_diary/pet_diary/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('pets/', include('pets.urls', namespace='pets')),
    path('', include('accounts.urls', namespace='accounts')),
    # path('', include('telegram_bot.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diploma/pet_diary/pets/urls.py
from django.urls import path

import pets.views

app_name = 'pets'

urlpatterns = [
    # PET
    path('', pets.views.pet.pet_list, name='pet_list'),
    path('create/', pets.views.pet.create_pet, name='pet_create'),
    path('<int:pet_id>/', pets.views.pet.pet_detail, name='pet_detail'),
    path('<int:pet_id>/edit/', pets.views.pet.edit_pet, name='pet_update'),
    path('<int:pet_id>/delete/', pets.views.pet.delete_pet, name='pet_delete'),

    # TASK
    path('<int:pet_id>/tasks/create/', pets.views.task.create_task, name='task_create'),
    path('tasks/<int:task_id>/edit/', pets.views.task.edit_task, name='task_edit'),
    path('tasks/<int:task_id>/delete/', pets.views.task.delete_task, name='task_delete'),
    path('<int:pet_id>/tasks/bulk_status/', pets.views.task.bulk_update_task_status, name='task_bulk_status'),

    # WEIGHT LOG
    path('<int:pet_id>/weight/create/', pets.views.weight_record.create_weight_record, name='weight_create'),
    path('weight/<int:weight_id>/edit/', pets.views.weight_record.edit_weight_record, name='weight_edit'),
    path('weight/<int:weight_id>/delete/', pets.views.weight_record.delete_weight_record, name='weight_delete'),

    # PHOTOS
    path('<int:pet_id>/photos/upload/', pets.views.image.upload_pet_image, name='photo_upload'),
    path('<int:pet_id>/image/<int:image_id>/edit/', pets.views.image.edit_pet_image, name='edit_pet_image'),
    path('<int:pet_id>/image/<int:image_id>/delete/', pets.views.image.delete_pet_image, name='delete_pet_image'),
    path('protected-media/<int:pet_id>/<str:image_name>/', pets.views.image.download_pet_image, name='protected_media'),

    # VACCINATIONS
    path('<int:pet_id>/vaccinations/create/', pets.views.vaccination.create_vaccination, name='vaccination_create'),
    path('vaccinations/<int:vacc_id>/edit/', pets.views.vaccination.edit_vaccination, name='vaccination_edit'),
    path('vaccinations/<int:vacc_id>/delete/', pets.views.vaccination.delete_vaccination, name='vaccination_delete'),

    # DOCUMENTS
    path('<int:pet_id>/documents/upload/', pets.views.document.upload_document, name='document_upload'),
    path('documents/<int:doc_id>/edit/', pets.views.document.edit_document, name='document_edit'),
    path('pet/<int:pet_id>/document/<int:doc_id>/delete/', pets.views.document.delete_document, name='delete_pet_document'),
    path('protected-media/documents/<int:pet_id>/<str:doc_name>/', pets.views.document.download_document, name='protected_media_document'),
]

diploma/pet_diary/pets/views/document.py
import mimetypes
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from pets.forms import PetDocumentForm
from pets.models import Pet, PetDocument


@login_required
def upload_document(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    if request.method == 'POST':
        form = PetDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            doc = form.save(commit=False)
            doc.pet = pet
            doc.doc_file_name = doc.doc_file.name
            doc.created_by = request.user
            if PetDocument.objects.filter(pet=pet, doc_file=request.FILES['doc_file']).exists():
                messages.error(request, "This document already exists.")
            else:
                doc.save()
                messages.success(request, _("Document uploaded successfully."))
                return redirect(f"{reverse('pets:pet_detail', args=[pet_id])}?tab=documents")
        else:
            messages.error(request, "Failed to upload document. Please correct the errors below.")
    else:
        form = PetDocumentForm()

    context = {
        'form': form,
        'pet': pet,
        'title': _("Add Document"),
    }
    return render(request, 'pets/document_form.html', context)


@login_required
def edit_document(request, doc_id):
    doc = get_object_or_404(PetDocument, id=doc_id, deleted_at__isnull=True)
    pet = doc.pet
    if request.method == 'POST':
        form = PetDocumentForm(request.POST, request.FILES, instance=doc)
        if form.is_valid():
            d = form.save(commit=False)
            d.mark_as_edited(request.user)
            d.save()
            return redirect(f"{reverse('pets:pet_detail', args=[pet.id])}?tab=documents")
    else:
        form = PetDocumentForm(instance=doc)

    return render(request, 'pets/document_form.html', {
        'form': form,
        'pet': pet,
        'title': _("Edit Document"),
        'document': doc,
    })


@login_required
def delete_document(request, pet_id, doc_id):
    pet = get_object_or_404(Pet, id=pet_id)

    if pet.owner != request.user and pet.caregiver != request.user:
        return HttpResponseForbidden(_("You do not have permission to delete this document."))

    pet_document = get_object_or_404(PetDocument, id=doc_id, pet=pet, deleted_at__isnull=True)

    if request.method == 'POST':
        pet_document.doc_file.delete(save=False)
        pet_document.mark_as_deleted(request.user)
        pet_document.doc_file.name = 'pet_documents/deleted_document.pdf'
        pet_document.save()
        messages.success(request, _("Document has been successfully deleted."))

        return redirect(f"{reverse('pets:pet_detail', args=[pet_id])}?tab=documents")
    else:
        return render(request, 'pets/document_confirm_delete.html', {
            'pet_document': pet_document,
            'pet': pet
        })


@login_required
def download_document(request, pet_id, doc_name):
    pet = get_object_or_404(Pet, id=pet_id)

    if pet.owner != request.user and pet.caregiver != request.user:
        return HttpResponseForbidden("You do not have permission to access this file.")

    try:
        document = PetDocument.objects.get(pet=pet, doc_file_name=doc_name, deleted_at__isnull=True)
    except PetDocument.DoesNotExist:
        return HttpResponseForbidden("File not found.")

    file_path = os.path.join(settings.MEDIA_ROOT, document.doc_file.name)
    if not os.path.exists(file_path):
        return HttpResponseForbidden("File not found.")

    mime_type, _ = mimetypes.guess_type(file_path)
    if not mime_type:
        mime_type = 'application/octet-stream'

    download = request.GET.get('download', '0')

    if download == '1':
        disposition = f'attachment; filename="{os.path.basename(file_path)}"'
    else:
        disposition = f'inline; filename="{os.path.basename(file_path)}"'

    try:
        file_handle = open(file_path, 'rb')
        response = FileResponse(file_handle, content_type=mime_type)
        response['Content-Disposition'] = disposition
        return response
    except Exception as e:
        return HttpResponseForbidden("Error accessing the file.")

diploma/pet_diary/pets/views/image.py
import mimetypes
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden, FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from pets.forms import PetImageForm
from pets.models import Pet, PetImage


@login_required
def upload_pet_image(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)

    if request.method == 'POST':
        form = PetImageForm(request.POST, request.FILES)
        if form.is_valid():
            pet_image = form.save(commit=False)
            pet_image.pet = pet
            pet_image.image_name = pet_image.path.name
            pet_image.created_by = request.user
            if PetImage.objects.filter(pet=pet, path=request.FILES['path']).exists():
                messages.error(request, "Such image already exists.")
            else:
                pet_image.save()
                messages.success(request, "Photo uploaded successfully.")

                tab = request.POST.get('tab', 'photos')
                view_photos = request.POST.get('view_photos', 'gallery')
                per_page_photos = request.POST.get('per_page_photos', '12')
                page_photos = request.POST.get('page_photos', '1')

                query_params = f"?tab={tab}&view_photos={view_photos}&per_page_photos={per_page_photos}&page_photos={page_photos}"
                return redirect(reverse('pets:pet_detail', args=[pet.id]) + query_params)
        else:
            messages.error(request, "Failed to upload photo. Please correct the errors below.")
    else:
        form = PetImageForm()

    context = {
        'form': form,
        'pet': pet,
    }
    return render(request, 'pets/forms/photo_form.html', context)


@login_required
def edit_pet_image(request, pet_id, image_id):
    pet = get_object_or_404(Pet, id=pet_id)
    pet_image = get_object_or_404(PetImage, id=image_id, pet=pet, deleted_at__isnull=True)

    if request.user != pet.owner and request.user != pet.caregiver:
        return HttpResponseForbidden(_("You do not have permission to edit this image."))

    if request.method == 'POST':
        form = PetImageForm(request.POST, request.FILES, instance=pet_image)
        if form.is_valid():
            if 'path' in form.changed_data:
                if PetImage.objects.filter(pet=pet, path=request.FILES.get('path')).exclude(id=image_id).exists():
                    messages.error(request, _("Such image already exists."))
                    return redirect(f"{reverse('pets:pet_detail', args=[pet_id])}?tab=photos&view_photos={request.POST.get('view_photos', 'gallery')}&per_page_photos={request.POST.get('per_page_photos', '12')}&page_photos={request.POST.get('page_photos', '1')}")
            form.save()
            messages.success(request, _("Image has been successfully updated."))

            tab = request.POST.get('tab', 'photos')
            view_photos = request.POST.get('view_photos', 'gallery')
            per_page_photos = request.POST.get('per_page_photos', '12')
            page_photos = request.POST.get('page_photos', '1')

            query_params = f"?tab={tab}&view_photos={view_photos}&per_page_photos={per_page_photos}&page_photos={page_photos}"
            return redirect(reverse('pets:pet_detail', args=[pet.id]) + query_params)
        else:
            messages.error(request, _("Failed to update image. Please correct the errors below."))
    else:
        form = PetImageForm(instance=pet_image)
        tab = request.GET.get('tab', 'photos')
        view_photos = request.GET.get('view_photos', 'gallery')
        per_page_photos = request.GET.get('per_page_photos', '12')
        page_photos = request.GET.get('page_photos', '1')

    context = {
        'form': form,
        'pet': pet,
        'title': _("Edit Image"),
        'pet_image': pet_image,
        'tab': tab if request.method == 'GET' else request.POST.get('tab', 'photos'),
        'view_photos': view_photos if request.method == 'GET' else request.POST.get('view_photos', 'gallery'),
        'per_page_photos': per_page_photos if request.method == 'GET' else request.POST.get('per_page_photos', '12'),
        'page_photos': page_photos if request.method == 'GET' else request.POST.get('page_photos', '1'),
    }
    return render(request, 'pets/forms/photo_form.html', context)


@login_required
def download_pet_image(request, pet_id, image_name):
    pet = get_object_or_404(Pet, id=pet_id)

    if pet.owner != request.user and pet.caregiver != request.user:
        return HttpResponseForbidden("You do not have permission to access this file.")

    try:
        image = PetImage.objects.get(pet=pet, image_name=image_name, deleted_at__isnull=True)
    except PetImage.DoesNotExist:
        return HttpResponseForbidden("File not found.")

    file_path = os.path.join(settings.MEDIA_ROOT, image.path.name)
    if not os.path.exists(file_path):
        return HttpResponseForbidden("File not found.")

    mime_type, _ = mimetypes.guess_type(file_path)
    if not mime_type:
        mime_type = 'application/octet-stream'

    download = request.GET.get('download', '0')

    if download == '1':
        disposition = f'attachment; filename="{os.path.basename(file_path)}"'
    else:
        disposition = f'inline; filename="{os.path.basename(file_path)}"'

    try:
        file_handle = open(file_path, 'rb')
        response = FileResponse(file_handle, content_type=mime_type)
        response['Content-Disposition'] = disposition
        return response
    except Exception as e:
        return HttpResponseForbidden("Error accessing the file.")


@login_required
def delete_pet_image(request, pet_id, image_id):
    pet = get_object_or_404(Pet, id=pet_id)

    if pet.owner != request.user and pet.caregiver != request.user:
        return HttpResponseForbidden(_("You do not have permission to delete this image."))

    pet_image = get_object_or_404(PetImage, id=image_id, pet=pet, deleted_at__isnull=True)

    tab = request.GET.get('tab', 'photos') if request.method == 'GET' else request.POST.get('tab', 'photos')
    view_photos = request.GET.get('view_photos', 'gallery') if request.method == 'GET' else request.POST.get('view_photos', 'gallery')
    per_page_photos = request.GET.get('per_page_photos', '12') if request.method == 'GET' else request.POST.get('per_page_photos', '12')
    page_photos = request.GET.get('page_photos', '1') if request.method == 'GET' else request.POST.get('page_photos', '1')

    if request.method == 'POST':
        pet_image.path.delete(save=False)
        pet_image.mark_as_deleted(request.user)
        pet_image.path.name = 'pet_images/deleted_image.jpg'
        pet_image.save()
        messages.success(request, _("Image has been successfully deleted."))

        tab = request.POST.get('tab', 'photos')
        view_photos = request.POST.get('view_photos', 'gallery')
        per_page_photos = request.POST.get('per_page_photos', '12')
        page_photos = request.POST.get('page_photos', '1')

        query_params = f"?tab={tab}&view_photos={view_photos}&per_page_photos={per_page_photos}&page_photos={page_photos}"
        return redirect(reverse('pets:pet_detail', args=[pet.id]) + query_params)
    else:
        return render(request, 'pets/image_confirm_delete.html', {
            'pet_image': pet_image,
            'pet': pet,
            'tab': tab,
            'view_photos': view_photos,
            'per_page_photos': per_page_photos,
            'page_photos': page_photos,
        })

diploma/pet_diary/pets/views/vaccination.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from pets.forms import VaccinationForm
from pets.models import Pet, Vaccination


@login_required
def create_vaccination(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    if request.method == 'POST':
        form = VaccinationForm(request.POST)
        if form.is_valid():
            vac = form.save(commit=False)
            vac.pet = pet
            vac.created_by = request.user
            vac.save()
            return redirect(f"{reverse('pets:pet_detail', args=[pet_id])}?tab=vaccinations")
    else:
        form = VaccinationForm()

    return render(request, 'pets/forms/vaccination_form.html', {
        'form': form,
        'pet': pet,
        'title': _("Add Vaccination"),
    })


@login_required
def edit_vaccination(request, vacc_id):
    vac = get_object_or_404(Vaccination, id=vacc_id, deleted_at__isnull=True)
    pet = vac.pet

    if request.user != pet.owner and request.user != pet.caregiver:
        return HttpResponseForbidden("You are not allowed to edit vaccination logs for this pet.")

    if request.method == 'POST':
        form = VaccinationForm(request.POST, request.FILES, instance=vac)
        if form.is_valid():
            v = form.save(commit=False)
            v.mark_as_edited(request.user)
            v.save()
            return redirect(f"{reverse('pets:pet_detail', args=[pet.id])}?tab=vaccinations")
    else:
        form = VaccinationForm(instance=vac)

    return render(request, 'pets/forms/vaccination_form.html', {
        'form': form,
        'pet': pet,
        'title': _("Edit Vaccination"),
        'vaccination': vac,
    })


@login_required
def delete_vaccination(request, vacc_id):
    vaccination_log = get_object_or_404(Vaccination, id=vacc_id, deleted_at__isnull=True)
    pet = vaccination_log.pet

    if request.user != pet.owner:
        return HttpResponseForbidden("You are not allowed to delete vaccination logs for this pet.")

    if request.method == 'POST':
        vaccination_log.mark_as_deleted(request.user)
        vaccination_log.save()
        return redirect(f"{reverse('pets:pet_detail', args=[pet.id])}?tab=vaccinations")

    return render(request, 'pets/vaccination_confirm_delete.html', {
        'vaccination_log': vaccination_log,
        'pet': pet
    })

diploma/pet_diary/templates/pets/pet_detail_tabs/documents.html
{% load i18n %}
{% load pagination %}
{% if active_tab == "documents" %}
  <div class="tab-pane fade show active" id="documents">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="m-0">{% trans "Pet Documents" %}</h5>
      <a href="{% url 'pets:document_upload' pet.id %}" class="btn btn-primary">
        {% trans "Upload Document" %}
      </a>
    </div>

    <div class="mb-3 d-flex justify-content-end">
      <form method="get" class="d-inline">
        <input type="hidden" name="tab" value="documents">
        <label for="id_per_page_documents">{% trans "Per page" %}:</label>
        <select name="per_page_documents" id="id_per_page_documents" onchange="this.form.submit()">
          <option value="10" {% if per_page_documents == "10" %}selected{% endif %}>10</option>
          <option value="25" {% if per_page_documents == "25" %}selected{% endif %}>25</option>
          <option value="50" {% if per_page_documents == "50" %}selected{% endif %}>50</option>
        </select>
      </form>
    </div>

    {% if documents %}
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th>{% trans "Document Date" %}</th>
            <th>{% trans "Type" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "File" %}</th>
            {% if request.user == pet.owner %}
              <th>{% trans "Actions" %}</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for doc in documents %}
            <tr>
              <td>{{ doc.doc_date }}</td>
              <td>{{ doc.get_doc_type_display }}</td>
              <td>{{ doc.description|default:"-" }}</td>
              <td>
                <a href="{% url 'pets:protected_media_document' pet.id doc.doc_file_name %}" target="_blank">
                  {% trans "Download" %}
                </a>
              </td>
              {% if request.user == pet.owner %}
                <td>
                  <a href="{% url 'pets:document_edit' doc.id %}" class="btn btn-sm btn-secondary">
                    {% trans "Edit" %}
                  </a>
                  <a href="{% url 'pets:delete_pet_document' pet.id doc.id %}" class="btn btn-sm btn-danger ms-1">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>

      {% render_pagination page_obj_documents "documents" "per_page_documents" "page_documents" %}
    {% else %}
      <p class="text-muted">{% trans "No pet documents available." %}</p>
    {% endif %}
  </div>
{% endif %}

diploma/pet_diary/templates/pets/pet_detail_tabs/tasks.html
{% load pagination %}
{% load i18n %}
{% if active_tab|default:"tasks" == "tasks" %}
  <div class="tab-pane fade show active" id="tasks">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="m-0">{% trans "Tasks" %}</h5>
      <a href="{% url 'pets:task_create' pet.id %}" class="btn btn-success">
        {% trans "Add Task" %}
      </a>
    </div>

    <!-- "Show/hide old" and "per_page" switches -->
    <div class="mb-3 d-flex justify-content-between">
      <div>
        {% if show_old == "1" %}
          <a
            href="?tab=tasks&show_old=0&per_page_tasks={{ per_page_tasks }}"
            class="btn btn-outline-secondary"
          >
            {% trans "Hide old tasks" %}
          </a>
        {% else %}
          <a
            href="?tab=tasks&show_old=1&per_page_tasks={{ per_page_tasks }}"
            class="btn btn-outline-secondary"
          >
            {% trans "Show old tasks" %}
          </a>
        {% endif %}
      </div>
      <div>
        <form method="get" class="d-inline">
          <!-- Saves current tab and show_old value at per_page selection -->
          <input type="hidden" name="tab" value="tasks">
          <input type="hidden" name="show_old" value="{{ show_old }}">

          <label for="id_per_page_tasks">{% trans "Per page" %}:</label>
          <select name="per_page_tasks" id="id_per_page_tasks" onchange="this.form.submit()">
            <option value="10" {% if per_page_tasks == "10" %}selected{% endif %}>10</option>
            <option value="25" {% if per_page_tasks == "25" %}selected{% endif %}>25</option>
            <option value="50" {% if per_page_tasks == "50" %}selected{% endif %}>50</option>
          </select>
        </form>
      </div>
    </div>

    {% if tasks %}
      <form method="POST" action="{% url 'pets:task_bulk_status' pet.id %}?tab=tasks&show_old={{ show_old }}&per_page_tasks={{ per_page_tasks }}">
        {% csrf_token %}
        <input type="hidden" name="bulk_update" value="1">

        <table class="table table-bordered table-sm">
          <thead>
            <tr>
              <th style="width: 40px;"></th>
              <th>{% trans "Title" %}</th>
              <th>{% trans "Due Date/Time" %}</th>
              <th>{% trans "Status" %}</th>
              <th style="width: 160px;">{% trans "Actions" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for task in tasks %}
              <tr>
                <td>
                  {% if task.status == 'planned' or task.status == 'overdue' %}
                    <input type="checkbox" name="task_ids" value="{{ task.id }}">
                  {% endif %}
                </td>
                <td>{{ task.title }}</td>
                <td>
                  {% if task.due_datetime %}{{ task.due_datetime }}{% else %}-{% endif %}
                </td>
                <td>
                  {% if task.status == 'planned' %}
                    <span class="badge bg-primary">{% trans "Planned" %}</span>
                  {% elif task.status == 'overdue' %}
                    <span class="badge bg-danger">{% trans "Overdue" %}</span>
                  {% elif task.status == 'done' %}
                    <span class="badge bg-success">{% trans "Done" %}</span>
                  {% elif task.status == 'skipped' %}
                    <span class="badge bg-secondary">{% trans "Skipped" %}</span>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'pets:task_edit' task.id %}" class="btn btn-sm btn-secondary">
                    {% trans "Edit" %}
                  </a>
                  {% if request.user == pet.owner %}
                    <a href="{% url 'pets:task_delete' task.id %}" class="btn btn-sm btn-danger ms-1">
                      {% trans "Delete" %}
                    </a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        <div class="mt-2">
          <button type="submit" name="action" value="done" class="btn btn-success btn-sm">
            {% trans "Mark as Done" %}
          </button>
          <button type="submit" name="action" value="skipped" class="btn btn-warning btn-sm">
            {% trans "Mark as Skipped" %}
          </button>
        </div>
      </form>

      {% render_pagination page_obj_tasks "tasks" "per_page_tasks" "page_tasks" %}
    {% else %}
      <p class="text-muted">{% trans "No tasks available." %}</p>
    {% endif %}
  </div>
{% endif %}

diploma/pet_diary/templates/pets/pet_detail_tabs/vaccination_log.html
{% load pagination %}
{% load i18n %}
{% if active_tab == "vaccinations" %}
  <div class="tab-pane fade show active" id="vaccinations">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="m-0">{% trans "Vaccination Log" %}</h5>
      <a href="{% url 'pets:vaccination_create' pet.id %}" class="btn btn-success">
        {% trans "Add Vaccination" %}
      </a>
    </div>

    <div class="mb-3 d-flex justify-content-end">
      <form method="get" class="d-inline">
        <input type="hidden" name="tab" value="vaccinations">
        <label for="id_per_page_vaccinations">{% trans "Per page" %}:</label>
        <select name="per_page_vaccinations" id="id_per_page_vaccinations" onchange="this.form.submit()">
          <option value="10" {% if per_page_vaccinations == "10" %}selected{% endif %}>10</option>
          <option value="25" {% if per_page_vaccinations == "25" %}selected{% endif %}>25</option>
          <option value="50" {% if per_page_vaccinations == "50" %}selected{% endif %}>50</option>
        </select>
      </form>
    </div>

    {% if vaccinations %}
      <table class="table table-bordered table-sm">
        <thead>
          <tr>
            <th>{% trans "Date Administered" %}</th>
            <th>{% trans "Vaccine Name" %}</th>
            <th>{% trans "Next Due Date" %}</th>
            <th>{% trans "Notes" %}</th>
            {% if request.user == pet.owner %}
              <th>{% trans "Actions" %}</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for vac in vaccinations %}
            <tr>
              <td>{{ vac.date_administered }}</td>
              <td>{{ vac.vaccine_name }}</td>
              <td>{{ vac.next_due_date|default:"-" }}</td>
              <td>{{ vac.notes|default:"-" }}</td>
              {% if request.user == pet.owner %}
                <td>
                  <a href="{% url 'pets:vaccination_edit' vac.id %}" class="btn btn-sm btn-secondary">
                    {% trans "Edit" %}
                  </a>
                  <a href="{% url 'pets:vaccination_delete' vac.id %}" class="btn btn-sm btn-danger ms-1">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>

      {% render_pagination page_obj_vaccinations "vaccinations" "per_page_vaccinations" "page_vaccinations" %}
    {% else %}
      <p class="text-muted">{% trans "No vaccination logs available." %}</p>
    {% endif %}
  </div>
{% endif %}

diploma/pet_diary/templates/pets/pet_detail_tabs/weight_log.html
{% load pagination %}
{% load i18n %}
{% if active_tab == "weight" %}
  <div class="tab-pane fade show active" id="weight">
    <div class="d-flex justify-content-between align-items-center mb-2">
      <h5 class="m-0">{% trans "Weight Log" %}</h5>
      <a href="{% url 'pets:weight_create' pet.id %}" class="btn btn-success">
        {% trans "Add Weight" %}
      </a>
    </div>

    <div class="mb-3 d-flex justify-content-end">
      <form method="get" class="d-inline">
        <input type="hidden" name="tab" value="weight">
        <label for="id_per_page_weight">{% trans "Per page" %}:</label>
        <select name="per_page_weight" id="id_per_page_weight" onchange="this.form.submit()">
          <option value="10" {% if per_page_weight == "10" %}selected{% endif %}>10</option>
          <option value="25" {% if per_page_weight == "25" %}selected{% endif %}>25</option>
          <option value="50" {% if per_page_weight == "50" %}selected{% endif %}>50</option>
        </select>
      </form>
    </div>

    {% if weight_logs %}
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Weight (kg)" %}</th>
            {% if request.user == pet.owner %}
              <th>{% trans "Actions" %}</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for wl in weight_logs %}
            <tr>
              <td>{{ wl.date }}</td>
              <td>{{ wl.weight_kg }} kg</td>
              {% if request.user == pet.owner %}
                <td>
                  <a href="{% url 'pets:weight_edit' wl.id %}" class="btn btn-sm btn-secondary">
                    {% trans "Edit" %}
                  </a>
                  <a href="{% url 'pets:weight_delete' wl.id %}" class="btn btn-sm btn-danger ms-1">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>

      {% render_pagination page_obj_weight "weight" "per_page_weight" "page_weight" %}
    {% else %}
      <p class="text-muted">{% trans "No weight logs available." %}</p>
    {% endif %}
  </div>
{% endif %}